version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: blog_api
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-backend:latest
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/blog_db?schema=public"
    depends_on:
      - db

volumes:
  postgres_data:
